"""cange type data nomor_tlpn

Revision ID: c91a14e401ba
Revises: e039aa2f1ffd
Create Date: 2022-06-21 12:37:55.526019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91a14e401ba'
down_revision = 'e039aa2f1ffd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
