"""solve one to one relationship

Revision ID: e1ee88ac63a2
Revises: 0d6d15341258
Create Date: 2022-06-21 12:17:14.649067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ee88ac63a2'
down_revision = '0d6d15341258'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
